sudo: required
language: node_js
node__js:
  - 7.7.4
before_install:
  - "echo Branch: ${TRAVIS_BRANCH}"
  - "echo PR: ${TRAVIS_PULL_REQUEST}"
  - sudo apt-get update
script:
  - npm install
after_success:
  - "echo It was successful"