sudo: required
language: node_js
node__js:
  - 7.7.4
before_install:
  - "echo --------- STARTING ---------"
  - "echo Branch: ${TRAVIS_BRANCH}"
  - "echo PR: ${TRAVIS_PULL_REQUEST}"
  - "sudo apt-get update"
script:
  - npm install
after_success:
  - docker --version
  - docker build -q -t brett-${TRAVIS_COMMIT} .;
  - "echo --------- FINISHED ---------"